### ISSUE TITLE
/api/get_user_best accuracy

### ISSUE THREAD

**Issue by Sakisan** [peppy/osu-api#80]
```/api/get_user_best``` currently provides
```
{
    "beatmap_id": "98615",
    "score": "10530008",
    "maxcombo": "717",
    "count50": "0",
    "count100": "17",
    "count300": "537",
    "countmiss": "0",
    "countkatu": "14",
    "countgeki": "105",
    "perfect": "1",
    "enabled_mods": "64",
    "user_id": "1011389",
    "date": "2014-08-13 00:50:44",
    "rank": "S"
    "pp": "255.529"
  }
```
which does not include the accuracy
Could it be included please?

**Comment by Sakisan** [comment]
I need to reopen this issue because the accuracy for osu!mania can't be calculated as there is no "count200" or "CountMAXes".

Reference: https://osu.ppy.sh/wiki/Accuracy

So the api should provides these counts or it should provide the accuracy out of the box.

**Comment by smoogipooo** [comment]
`countkatu` is 200, `countgeki` is MAX.

**Comment by Sakisan** [comment]
confirmed
