### ISSUE TITLE
More data for /get_beatmaps like genre

### ISSUE THREAD

**Issue by LemonLube** [peppy/osu-api#87]
I'm enjoying the api at the moment however recently I've found a need for data such as the genre. I soon came to realize that there was no such field stored for it as well as a few other things that are lower priority for my app but would be nice regardless (tags, min/max bpm, user ratings, total track length and success rate).

I understand that there are other methods for obtaining similar information for instance using the already obtainable artist and title, and searching in a separate music database api but obviously that's not going to be the same.

**Comment by peppy** [comment]
genres:
```
0	Any
1	Unspecified
2	Video Game
3	Anime
4	Rock
5	Pop
6	Other
7	Novelty
9	Hip Hop
10	Electronic
```

langauges:
```
0	Any
1	Other
2	English
3	Japanese
4	Chinese
5	Instrumental
6	Korean
7	French
8	German
9	Swedish
10	Spanish
11	Italian
```

Please add to documentation.

**Comment by LemonLube** [comment]
Already there. Much appreciated!
