### ISSUE TITLE
More than 50 scores for each map

### ISSUE THREAD

**Issue by rllin** [peppy/osu-api#88]
Maybe there's already a way to do this.  I just want to see a distribution of performance for each map.  The first 50 are obviously top percentile players and will all have very similar scores.  Not very useful for getting an idea of how well people do overall on each map.

**Comment by TheHowl** [comment]
This should rather be in feature requests, as it would be better for it to be in all the game, not just the API.

**Comment by FullTablet** [comment]
https://osu.ppy.sh/forum/t/329678
Having a full list of scores would be useful for the accuracy of the algorithm used there.
Currently, the only way to obtain score information of scores beyond top 50 scores or player performances is calling /api/get_scores with a specific user_id and beatmap_id for each possible combination (which requires many API calls, and takes a very long time).

**Comment by peppy** [comment]
Increased from 50 to 100. I know this doesn't necessarily give you the data you want still, but let's agree it's an improvement for now.

**Comment by TheHowl** [comment]
Wiki updated.

**Comment by Ziggo64** [comment]
I just tried getting some scores and only got the top 50 ranks. Is there a parameter for this? I can't find one in the Wiki though.

**Comment by peppy** [comment]
Needs to be added to wiki. Parameter is `limit`, default is 50, maximum is 100.

**Comment by Ziggo64** [comment]
Wiki updated. Thanks for the quick response.
