### ISSUE TITLE
get_user get all modes

### ISSUE THREAD

**Issue by Nipah887** [peppy/osu-api#89]
As the title suggests the ability to get data off all game modes for one user.

https://osu.ppy.sh/api/get_user?k=myKey&u=4041778&m=all
[{osu_ranked_score:'',osu_pp_rank:'',osu_level:'',mania_ranked_score:'',taiko_ranked_score... you get the idea

I'm currently looping an update script every 2 seconds to get data on each players osu, mania, taiko and ctb ranks. It's very inefficient for me and adds unnecessary requests on http://osu.ppy.sh/api

This is my little pet project http://verylazy.net/osu/

**Comment by peppy** [comment]
per-mode is the most efficient access method at our end, so the extra requests aren't really "unnecessary" or "inefficient".
