### ISSUE TITLE
osu:// URL schema?

### ISSUE THREAD

**Issue by gdude2002** [peppy/osu-api#96]
I don't play Osu! myself, but I support an extension in my bot's URL handler that uses the Osu! API to retrieve information about a URL.

I've recently added support for non-`http/s` URLs, and I've noticed that there are `osu://` URLs, but I can't find documentation on the URL spec or every command that it may contain.

It'd be great to be able to support these in my URL handler as well - any chance on some documentation for this?

**Comment by TheHowl** [comment]
There isn't really a spec, as they shouldn't really have an use on other places apart from osu! and the osu! website (which only really actually uses it for edit links). Anyway, here's some sort of unofficial spec (there might be more links that aren't public or that I've missed!)

schema                                                                  | Description
----------------------------------------------------------------|---------------------------
`osu://mp/<int mpID>[/<string password>]`  | Link to a multiplayer match. mpID is an ID to a multiplayer match (does not work with the API call `/api/get_match`!), while password is the password to the multiplayer lobby (if it has one, that is). 
`osu://edit/<xx:xx:xxx>[ (x,x,x,x...)]`                   | (x is an int from 0 to 9). xx:xx:xxx is a position in time of a song, while x,x,x,x,x (can be as many as you wish) are hit objects (sliders, circles, spinners) that have been selected. this link is added automatically in mods (for instance, [this one is a mod](https://osu.ppy.sh/forum/p/3749275)) when `xx:xx:xxx (x,x,x,x...)` is written. It usually isn't written by hand, usually modders select a few notes from the in-game editor and use ctrl+c to copy `xx:xx:xxx (x,x,x,x...)` to clipboard.
`osu://chan/#<string ChanName>`                 | Link to a channel in the osu! chat. (e.g. osu://chan/#italian). When clicked, the channel is automatically opened in osu!. If you want to do a sort of integration of your tool, you can change it with an irc link to cho.ppy.sh on channel ChanName, although it will require authentication with a password that can be obtained [going to this page](https://osu.ppy.sh/p/ircauth).
`osu://dl/<int mapsetID>`                                  | Link to an osu!direct download. osu!direct is a [supporter](https://osu.ppy.sh/p/support)-only feature. You can get data of the beatmap by doing an api request (`/api/get_beatmap?k=<api key>&s=<mapsetID>`)

**Comment by peppy** [comment]
Would probably pay to add this to the wiki section rather than letting it sit in an issue.

**Comment by hypereddie** [comment]
I've gone ahead and put the table in the wiki under [Reference](https://github.com/peppy/osu-api/wiki#reference)

**Comment by peppy** [comment]
Thanks much.
